Fix #4 `rake` failure with rbenv
Use OS X bundled Ruby to build RubyCocoa.framework

Because if use Ruby which installed via rbenv, it will causes error.

```
$ rbenv version
2.2.2 (set by RBENV_VERSION environment variable)

$ rake
/Users/watson/.rbenv/versions/2.2.2/bin/ruby install.rb config
install.rb: entering config phase...
config failed
hook /Users/watson/src/github/rubycocoa/./pre-config.rb failed:
ERROR: ruby must be built as a shared library
try 'ruby install.rb --help' for usage
rake aborted!
Command failed with status (1): [/Users/watson/.rbenv/versions/2.2.2/bin/ru...]
/Users/watson/src/github/rubycocoa/Rakefile:25:in `block in <top (required)>'
Tasks: TOP => default => build
(See full trace by running task with --trace)
```